spring:
  data:
    mongodb:
      username: vietquan
      password: vietquan
      additional-hosts: localhost
      port: 27017
      database: customer
      authentication-database: admin

server:
  port: 8090